
version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm test
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket code.people.pillartechnology.com --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
    - xunit.xml
